### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by EmanYm** [FabioZumbi12/Sponge-Signedit#2]
Is this wip or abandoned?
API and MC version?
Client or Server?

**Comment by FabioZumbi12** [comment]
Its released on Sponge forum: https://forums.spongepowered.org/t/ledger-signeditor-simple-sign-editor-1-8-9-1-11-2/14589

**Comment by EmanYm** [comment]
Thank you for the swift responce.
I knew it was for sponge, that's how I found you. :P
I says 1.8.9 and 1.11.2...so no 1.10.2?  Or will this work for all versions between the two?  I can't imagine the raw code for signs has changed drastically between the versions, so this could theoretically work.

**Comment by JonathanBrouwer** [comment]
It is from 1.8.9 to 1.11.2

**Comment by EmanYm** [comment]
Thank you for clearing this up.

**Comment by EmanYm** [comment]
Is there an API 5 version, or do you have plans to make a version for it?

**Comment by FabioZumbi12** [comment]
What errors are you having?

**Comment by EmanYm** [comment]
I haven't tried using it yet, but my understanding is that API versions are not backward compatible.  I asked Aaron1011 about using API5 plugins in an API6 environment, and this is what he responded with:

>API 6 is intetionally not backwards compatbilie, unfortunately. Any breaking changes we make to the API will be done in the next major version (API 6 in this case).

I can try to use it in a single player world and report back if you want me to.

**Comment by FabioZumbi12** [comment]
With little plugins like this you will not have api problems. Use and report here if you found erros or close if works ;)

**Comment by EmanYm** [comment]
In single player it did not work even when I opened to LAN.

I uploaded it to my server and restarted.
Found this in my console:
>[11:39:48] [Server thread/WARN] [Sponge]: The mod signeditor was designed for spongeapi 6.0.0-SNAPSHOT but version 5.1.0-SNAPSHOT-6459642 is in use. It may not work properly.

Continued to load with no further issues.


`/signedit ?` works
Placed a simple sign with numbers 1-4 on separate lines.
`/setline 1 test`  then clicked the sign works.

Conclusion:
Even though it says `API 6` in the mcmod.info file, it does in fact function as intended in an API5 environment.
You could include that on your sponge description for anyone else that may be confused about it.


(You can close this once you read it.)
