### ISSUE TITLE
[Request] update to API 7

### ISSUE THREAD

**Issue by bhi-elliot** [FabioZumbi12/Sponge-Signedit#5]
Please and thank you.

**Comment by FabioZumbi12** [comment]
Already is working on API 7, i have teste! What errors are you having? Can you paste on pastebin the error logs from console?

**Comment by bhi-elliot** [comment]
Hello,
Thank you for the reply.
I was receiving just a warning from server console, nothing major. I just put this here to let you know we love your plugin and would be grateful if it were updated.
I am happy to hear you are updating it. I really appreciate it.
